parser: babel-eslint
env:
    es6: true
    browser: true
    node: true
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true
    sourceType: module
globals:
    describe: true
    test: true
    expect: true
plugins:
    - import
extends:
    - plugin:import/errors
    - plugin:import/warnings
rules:
    array-bracket-spacing: [error, never]
    arrow-parens: [error, as-needed]
    eol-last: 0
    jsx-quotes: [error, prefer-single]
    new-cap: 0
    no-debugger: 1
    no-undef: 2
    no-underscore-dangle: 0
    no-unused-vars: [error, {vars: all, args: none, varsIgnorePattern: _+}]
    no-use-before-define: 0
    object-curly-spacing:  [error, never]
    quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
    semi: [error, never]
    strict: 0
